universe = vanilla
executable = /het/p4/dshih/jet_images-deep_learning/RL_MIR_IBP/conda_env/bin/python
arguments = -u /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/scripts/eval/onestep_worker.py --topology /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/topology_input/pentagonbox --integral='0,5,1,1,1,1,1,1,0,0,0' --output /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/results/probe_l7_high_r/result.pkl --model-checkpoint /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/checkpoints/pentagonbox_v2/best_model.pt --beam_width 20 --max_steps 1000000 --prime 1009 --device cpu -v --n_workers 8
output = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/results/probe_l7_high_r/probe.out
error  = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/results/probe_l7_high_r/probe.err
log    = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/results/probe_l7_high_r/probe.log
request_cpus = 8
request_memory = 32GB
request_disk = 1GB
Requirements = (TARGET.KFlops > 3000000)
+JobFlavour = "workday"
queue
