#!/bin/bash
# Submit Condor jobs to generate self-supervised training data in parallel.
# Default: 100 jobs * 1000 scrambles = 100 000 scrambles attempted, of
# which ~18% are skipped (vanishing corners), giving the ~80k successful
# trajectories quoted in the paper (§IV.B).  Reproduces the data the
# published checkpoint was trained on.
#
# Usage:  ./submit_datagen.sh [n_jobs] [scrambles_per_job]
#
# Required env vars:
#   SAILIR_DIR  -- absolute path to the SAILIR repo root
#   PYTHON      -- python interpreter to use inside workers (default: python3)

set -e

if [[ -z "${SAILIR_DIR:-}" ]]; then
    echo "ERROR: set SAILIR_DIR to the repo root before running." >&2
    exit 1
fi

N_JOBS=${1:-100}
SCRAMBLES_PER_JOB=${2:-1000}
OUTPUT_DIR="${OUTPUT_DIR:-${SAILIR_DIR}/data/raw_jsonl}"
CONDOR_DIR="${SAILIR_DIR}/scripts/data_gen"

echo "========================================"
echo "SAILIR data-gen Condor submission"
echo "========================================"
echo "Number of jobs:     ${N_JOBS}"
echo "Scrambles per job:  ${SCRAMBLES_PER_JOB}"
echo "Total scrambles:    $((N_JOBS * SCRAMBLES_PER_JOB))"
echo "Output directory:   ${OUTPUT_DIR}"
echo "========================================"

mkdir -p "${OUTPUT_DIR}" "${CONDOR_DIR}/logs"
chmod +x "${CONDOR_DIR}/datagen_worker.sh"

JDL_FILE="${CONDOR_DIR}/datagen_job_custom.jdl"
cat > "${JDL_FILE}" << EOF
# Auto-generated by submit_datagen.sh
universe                 = vanilla
executable               = ${CONDOR_DIR}/datagen_worker.sh
arguments                = \$(Process) ${SCRAMBLES_PER_JOB} ${OUTPUT_DIR}
output                   = ${CONDOR_DIR}/logs/datagen_\$(Process).out
error                    = ${CONDOR_DIR}/logs/datagen_\$(Process).err
log                      = ${CONDOR_DIR}/logs/datagen_\$(Process).log
environment              = "SAILIR_DIR=${SAILIR_DIR} PYTHON=${PYTHON:-python3}"
request_cpus             = 1
request_memory           = 4GB
request_disk             = 1GB
should_transfer_files    = NO
notification             = Error
queue ${N_JOBS}
EOF

echo "Wrote ${JDL_FILE}"
echo
echo "To submit:   condor_submit ${JDL_FILE}"
echo "To monitor:  condor_q"
echo "When done:   ./merge_outputs.sh ${OUTPUT_DIR}"
