#!/bin/bash
# Submit Condor jobs to generate pentagon-box (TA) training data in parallel.
# Default: 100 jobs * 1000 scrambles = 100 000 attempted scrambles, same scale
# as the published trianglebox dataset.
#
# Pentagon-box has ~144/255 corners vanishing (Kira-trivial), so expect a
# lower successful-trajectory yield than trianglebox. Scale N_JOBS up if more
# successful trajectories are wanted.
#
# Usage:  ./submit_datagen_pentagonbox.sh [n_jobs] [scrambles_per_job]
#
# Required env vars:
#   SAILIR_DIR  -- absolute path to the SAILIR_phase2 repo root
#   PYTHON      -- python interpreter to use inside workers

set -e

if [[ -z "${SAILIR_DIR:-}" ]]; then
    echo "ERROR: set SAILIR_DIR to the repo root before running." >&2
    exit 1
fi

N_JOBS=${1:-100}
SCRAMBLES_PER_JOB=${2:-1000}
OUTPUT_DIR="${OUTPUT_DIR:-${SAILIR_DIR}/data/pentagonbox_raw_jsonl}"
CONDOR_DIR="${SAILIR_DIR}/scripts/data_gen"

echo "========================================"
echo "SAILIR pentagon-box data-gen Condor submission"
echo "========================================"
echo "Number of jobs:     ${N_JOBS}"
echo "Scrambles per job:  ${SCRAMBLES_PER_JOB}"
echo "Total scrambles:    $((N_JOBS * SCRAMBLES_PER_JOB))"
echo "Output directory:   ${OUTPUT_DIR}"
echo "Topology:           topology_input/pentagonbox"
echo "========================================"

mkdir -p "${OUTPUT_DIR}" "${CONDOR_DIR}/logs"
chmod +x "${CONDOR_DIR}/datagen_worker_pentagonbox.sh"

JDL_FILE="${CONDOR_DIR}/datagen_pentagonbox.jdl"
cat > "${JDL_FILE}" << EOF
# Auto-generated by submit_datagen_pentagonbox.sh
universe                 = vanilla
executable               = ${CONDOR_DIR}/datagen_worker_pentagonbox.sh
arguments                = \$(Process) ${SCRAMBLES_PER_JOB} ${OUTPUT_DIR}
output                   = ${CONDOR_DIR}/logs/datagen_pb_\$(Process).out
error                    = ${CONDOR_DIR}/logs/datagen_pb_\$(Process).err
log                      = ${CONDOR_DIR}/logs/datagen_pb_\$(Process).log
environment              = "SAILIR_DIR=${SAILIR_DIR} PYTHON=${PYTHON:-python3}"
request_cpus             = 1
request_memory           = 6GB
request_disk             = 1GB
should_transfer_files    = NO
notification             = Error
queue ${N_JOBS}
EOF

echo "Wrote ${JDL_FILE}"
echo
echo "To submit:   /usr/bin/condor_submit ${JDL_FILE}"
echo "To monitor:  /usr/bin/condor_q"
echo "When done:   ./merge_outputs_pentagonbox.sh ${OUTPUT_DIR}"
