#!/bin/bash
# Setup and submit multi-sector IBP data generation jobs to condor
# Usage: ./submit_datagen.sh [n_jobs] [scrambles_per_job]

N_JOBS=${1:-100}
SCRAMBLES_PER_JOB=${2:-1000}

BASE_DIR=/het/p4/dshih/jet_images-deep_learning/RL_IBPreduction_claude
CONDOR_DIR=${BASE_DIR}/scripts/condor
OUTPUT_DIR=${BASE_DIR}/data/multisector

echo "========================================"
echo "Multi-sector IBP Data Generation Setup"
echo "========================================"
echo "Number of jobs: ${N_JOBS}"
echo "Scrambles per job: ${SCRAMBLES_PER_JOB}"
echo "Total scrambles: $((N_JOBS * SCRAMBLES_PER_JOB))"
echo "Sectors: ALL 63"
echo "Output directory: ${OUTPUT_DIR}"
echo "========================================"

# Create directories
mkdir -p ${CONDOR_DIR}/logs
mkdir -p ${OUTPUT_DIR}

# Make worker script executable
chmod +x ${CONDOR_DIR}/datagen_worker.sh

# Generate JDL file with custom parameters
JDL_FILE=${CONDOR_DIR}/datagen_job_custom.jdl

cat > ${JDL_FILE} << EOF
# Condor JDL for multi-sector IBP data generation
# Auto-generated by submit_datagen.sh

universe = vanilla
executable = ${CONDOR_DIR}/datagen_worker.sh

# Arguments: worker_id n_scrambles output_dir
arguments = \$(Process) ${SCRAMBLES_PER_JOB} ${OUTPUT_DIR}

# Logging
output = ${CONDOR_DIR}/logs/datagen_\$(Process).out
error = ${CONDOR_DIR}/logs/datagen_\$(Process).err
log = ${CONDOR_DIR}/logs/datagen_\$(Process).log

# Resource requirements
request_cpus = 1
request_memory = 4GB
request_disk = 1GB

# Don't transfer files - use shared filesystem
should_transfer_files = NO

# Notification
notification = Error

# Queue jobs
queue ${N_JOBS}
EOF

echo "Generated JDL file: ${JDL_FILE}"
echo ""
echo "To submit jobs, run:"
echo "  condor_submit ${JDL_FILE}"
echo ""
echo "To check job status:"
echo "  condor_q"
echo ""
echo "After jobs complete, merge outputs with:"
echo "  cat ${OUTPUT_DIR}/multisector_data_worker*.jsonl > ${OUTPUT_DIR}/multisector_training_data.jsonl"
echo ""
echo "To count total samples:"
echo "  wc -l ${OUTPUT_DIR}/multisector_training_data.jsonl"
