universe = vanilla
executable = /het/p4/dshih/jet_images-deep_learning/RL_MIR_IBP/conda_env/bin/python
arguments = -u /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/scripts/train/finetune_v2_on_sec254.py
output = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/checkpoints/pentagonbox_sec254_finetune_v1/condor.out
error  = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/checkpoints/pentagonbox_sec254_finetune_v1/condor.err
log    = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/checkpoints/pentagonbox_sec254_finetune_v1/condor.log
request_cpus = 4
request_memory = 32GB
request_disk = 20GB
request_gpus = 2
should_transfer_files = NO
queue 1
