universe = vanilla
executable = /het/p4/dshih/jet_images-deep_learning/RL_MIR_IBP/conda_env/bin/python
arguments = -u /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/data-gen/generate_multisector_data.py --topology /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/topology_input/pentagonbox --n_scrambles 200 --min_steps 5 --max_steps 20 --restrict-sectors 254 --bias-low-s-elim --output /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/data/pilot_bias_low_s/pilot_B_worker$(Process).jsonl --start_seed $(Process)0000 --prime 1009
output = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/data/pilot_bias_low_s/pilot_B_worker$(Process).out
error  = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/data/pilot_bias_low_s/pilot_B_worker$(Process).err
log    = /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2/data/pilot_bias_low_s/pilot_B_worker$(Process).log
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
Requirements = (TARGET.KFlops > 3000000)
+JobFlavour = "workday"
queue 4
