#!/bin/bash
# Smoke test: preprocess the small JSONL files generated by run_datagen_smoke.sh
# into tensor files, then check that train_classifier.py --help works.
set -u
cd /het/p4/dshih/jet_images-deep_learning/SAILIR_phase2
mkdir -p scripts/symmetries/logs
PY=/het/p4/dshih/jet_images-deep_learning/RL_MIR_IBP/conda_env/bin/python

LOG=scripts/symmetries/logs/preprocess_train_smoke.log
: > $LOG

echo "==== preprocess trianglebox ====" >> $LOG
PYTHONUNBUFFERED=1 "$PY" -u scripts/data_gen/preprocess_to_tensors.py \
    --topology topology_input/trianglebox \
    --input scripts/symmetries/tmp_datagen/tb_smoke.jsonl \
    --output_dir scripts/symmetries/tmp_datagen/tb_packed \
    --val_split 0.2 --test_split 0.2 \
    >> $LOG 2>&1
echo "tb preprocess exit=$?" >> $LOG

echo >> $LOG
echo "==== preprocess pentagon-box ====" >> $LOG
PYTHONUNBUFFERED=1 "$PY" -u scripts/data_gen/preprocess_to_tensors.py \
    --topology topology_input/pentagonbox \
    --input scripts/symmetries/tmp_datagen/pb_smoke.jsonl \
    --output_dir scripts/symmetries/tmp_datagen/pb_packed \
    --val_split 0.2 --test_split 0.2 \
    >> $LOG 2>&1
echo "pb preprocess exit=$?" >> $LOG

echo >> $LOG
echo "==== train_classifier.py --help ====" >> $LOG
PYTHONUNBUFFERED=1 "$PY" -u scripts/train/train_classifier.py --help >> $LOG 2>&1
echo "train --help exit=$?" >> $LOG

cat $LOG | tail -40
